#!/bin/bash
#Make some keys for testing


for i in {1..30}
do
	echo $i
	openssl genrsa -out priv_key/node$i.pem 4096
	openssl rsa -in priv_key/node$i.pem -pubout > pub_key/node$i.pub
done

echo "30 public/private keys generated"
